#ifndef UE4SS_SDK_BP_PersonCharacter_HPP
#define UE4SS_SDK_BP_PersonCharacter_HPP

class ABP_PersonCharacter_C : public AEHCharacter
{
    FPointerToUberGraphFrame UberGraphFrame;
    class UTextRenderComponent* TextRender;
    class UNiagaraComponent* MP_NGThruster;
    class UStaticMeshComponent* MP_Jetpack;
    class UStaticMeshComponent* MP_Head;
    class UStaticMeshComponent* MP_Tool;
    class USceneComponent* ParticleTest;
    class UCameraComponent* Camera;
    class USpringArmComponent* SpringArm;
    class UStaticMeshComponent* TorusEffect;
    class UStaticMeshComponent* SphereEffect;
    class UStaticMeshComponent* Tool;
    class USceneComponent* ToolRoot;
    class UWidgetInteractionComponent* WidgetInteraction;
    class USceneComponent* VertexCollapsePoint;
    class UVoxelSimpleInvokerComponent* VoxelInvoker;
    class USkeletalMeshComponent* Mesh2P;
    class UBP_InventoryComponent_C* BP_InventoryComponent;
    float Construct_0_1_DFBE78BF4CABD9B3B283D79A8A6B37A8;
    TEnumAsByte<ETimelineDirection::Type> Construct__Direction_DFBE78BF4CABD9B3B283D79A8A6B37A8;
    class UTimelineComponent* Construct;
    float Firing_0_1_A80367A64A47C013BC896FB345DBDCF9;
    TEnumAsByte<ETimelineDirection::Type> Firing__Direction_A80367A64A47C013BC896FB345DBDCF9;
    class UTimelineComponent* Firing;
    float Timeline_0_0_1_9CD6C19C477E3028C97CD4917AFCE755;
    TEnumAsByte<ETimelineDirection::Type> Timeline_0__Direction_9CD6C19C477E3028C97CD4917AFCE755;
    class UTimelineComponent* Timeline_0;
    float Scanner_Radius_42DF950144FE83DEEF949BA14B309CF0;
    TEnumAsByte<ETimelineDirection::Type> Scanner__Direction_42DF950144FE83DEEF949BA14B309CF0;
    class UTimelineComponent* Scanner;
    float EquipTimeline_0_1_82F8B89C448F3CC265841AB9A135ACD2;
    TEnumAsByte<ETimelineDirection::Type> EquipTimeline__Direction_82F8B89C448F3CC265841AB9A135ACD2;
    class UTimelineComponent* EquipTimeline;
    float FireOnce_0_1_1B7D6FCF407EEF2502B6D486D6EEFE42;
    TEnumAsByte<ETimelineDirection::Type> FireOnce__Direction_1B7D6FCF407EEF2502B6D486D6EEFE42;
    class UTimelineComponent* FireOnce;
    float BaseTurnRate;
    float BaseLookUpRate;
    FRotator StartWeaponRotation;
    FRotator EndWeaponRotation;
    FRotator ControlRotationCached;
    class UMaterialInstanceDynamic* SphereMaterialDyn;
    class UMaterialInstanceDynamic* TorusMaterialDyn;
    class AEHGrid* GridTestReference;
    class UDestructibleComponent* DestructibleTest;
    FBP_PersonCharacter_CItemDigged ItemDigged;
    void ItemDigged(FEHItemInstance Item);
    FBP_PersonCharacter_CVoxelDigged VoxelDigged;
    void VoxelDigged(FIntVector position);
    FIntVector VoxelPosition;
    bool IsRemovingVoxel;
    class AEHVoxelWorld* VoxelWorldCached;
    FVector CameraShaderOffset;
    bool ActionWasCanceled;

    FEHIndicationConfigData GetIndicationConfigData();
    FVector GetIndicationPosition();
    FText GetIndicationText();
    bool IsRegisteringForbidden();
    void MP_JetpackChanged(bool IsActive);
    class USceneComponent* GetInteractionComponent();
    void UpdateJetpackMovement();
    void UpdateBoosterMovement();
    void GetFarShaderOffset(FVector& ShaderOffset);
    void TeleportIfStuck();
    void TryPickDigItem(FVoxelTerrainDigData& DigData);
    void UpdateMovement();
    void UpdateVoxelPosition();
    void UpdateDefaultMovement();
    void ControlModeChanged();
    void UpdateTorusParams(bool Enabled);
    void UpdateSphereParams(bool Enabled);
    void CreateDynamicMaterials();
    void TryAddVoxel();
    void TryRemoveVoxel();
    void UpdateToolRotation(float Alpha);
    void ChangeToolMesh();
    void UserConstructionScript();
    void Firing__FinishedFunc();
    void Firing__UpdateFunc();
    void Firing__VoxelRemove__EventFunc();
    void Firing__Hit__EventFunc();
    void EquipTimeline__FinishedFunc();
    void EquipTimeline__UpdateFunc();
    void Scanner__FinishedFunc();
    void Scanner__UpdateFunc();
    void Timeline_0__FinishedFunc();
    void Timeline_0__UpdateFunc();
    void Timeline_0__VoxelAdd__EventFunc();
    void FireOnce__FinishedFunc();
    void FireOnce__UpdateFunc();
    void Construct__FinishedFunc();
    void Construct__UpdateFunc();
    void InpActEvt_Jump_K2Node_InputActionEvent_12(FKey Key);
    void InpActEvt_Jump_K2Node_InputActionEvent_11(FKey Key);
    void InpActEvt_U_K2Node_InputKeyEvent_6(FKey Key);
    void InpActEvt_Comma_K2Node_InputKeyEvent_5(FKey Key);
    void InpActEvt_SecondAction_K2Node_InputActionEvent_10(FKey Key);
    void InpActEvt_MouseScrollDown_K2Node_InputKeyEvent_4(FKey Key);
    void InpActEvt_ToolScan_K2Node_InputActionEvent_9(FKey Key);
    void InpActEvt_ToolPickaxe_K2Node_InputActionEvent_8(FKey Key);
    void InpActEvt_ActionInteract_K2Node_InputActionEvent_7(FKey Key);
    void InpActEvt_ActionOpen_K2Node_InputActionEvent_6(FKey Key);
    void InpActEvt_ActionRemoveSelected_K2Node_InputActionEvent_5(FKey Key);
    void InpActEvt_ActionRemove_K2Node_InputActionEvent_4(FKey Key);
    void InpActEvt_ActionSelect_K2Node_InputActionEvent_3(FKey Key);
    void InpActEvt_ActionSelect_K2Node_InputActionEvent_2(FKey Key);
    void InpActEvt_ActionUpgrade_K2Node_InputActionEvent_1(FKey Key);
    void InpActEvt_ActionCancel_K2Node_InputActionEvent_0(FKey Key);
    void InpActEvt_MiddleMouseButton_K2Node_InputKeyEvent_3(FKey Key);
    void InpActEvt_Slash_K2Node_InputKeyEvent_2(FKey Key);
    void OnLoaded_32A09A57484AB869B8782DB62ACC2B62(class UObject* Loaded);
    void OnLoaded_35DEB2E348229A65E29C2C875863E456(class UObject* Loaded);
    void OnLoaded_8B13DB2944E52C0458C612903BF90751(class UObject* Loaded);
    void OnLoaded_FD4CB23643E81748EC31799FFB92A933(class UObject* Loaded);
    void OnLoaded_51CD6D31468CE59A11819EB1CE6CB1D8(class UObject* Loaded);
    void OnLoaded_42184D4547809D09392EC1BE174F551E(class UObject* Loaded);
    void InpActEvt_Period_K2Node_InputKeyEvent_1(FKey Key);
    void InpActEvt_MouseScrollUp_K2Node_InputKeyEvent_0(FKey Key);
    void InpAxisEvt_LookUpRate_K2Node_InputAxisEvent_62(float AxisValue);
    void InpAxisEvt_TurnRate_K2Node_InputAxisEvent_34(float AxisValue);
    void ReceiveTick(float DeltaSeconds);
    void ReceiveBeginPlay();
    void BndEvt__WidgetInteraction_K2Node_ComponentBoundEvent_0_OnHoveredWidgetChanged__DelegateSignature(class UWidgetComponent* WidgetComponent, class UWidgetComponent* PreviousWidgetComponent);
    void LoadingGameData(class UEHSaveGame* SaveGame);
    void SavingGameData(class UEHSaveGame* SaveGame);
    void InpAxisEvt_LookUp_K2Node_InputAxisEvent_172(float AxisValue);
    void PlayEquipAnimation();
    void InpAxisEvt_Turn_K2Node_InputAxisEvent_157(float AxisValue);
    void UpdateShaderCameraPosition(FVector ShaderCameraPosition);
    void ReceiveUnpossessed(class AController* OldController);
    void ReceivePossessed(class AController* NewController);
    void Server_TeleportIfStuck();
    void Server_RemoveBox(class AEHVoxelWorld* VoxelWorld, const FVoxelIntBox& BoxBounds);
    void Client_NotifyNoDirt();
    void Server_AddVoxel(class AEHVoxelWorld* VoxelWorld, const FIntVector& Coord);
    void Scan();
    void UpdateMPTool();
    void DisableJetpackFloorCheck();
    void ExecuteUbergraph_BP_PersonCharacter(int32 EntryPoint);
    void VoxelDigged__DelegateSignature(FIntVector position);
    void ItemDigged__DelegateSignature(FEHItemInstance Item);
};

#endif
